Generate pems

diff --git a/templates/default/rstudio.sh.erb b/templates/default/rstudio.sh.erb
--- a/templates/default/rstudio.sh.erb
+++ b/templates/default/rstudio.sh.erb
@@ -8,19 +8,21 @@
 
 help() {
     echo ""
-    echo "usage: $0 [start rstudio_home hadoop_home project_user_name port secret_dir certs_dir hadoop_username
-     image_name logfile server_password hadoop_version hdfs_namenode_ip hdfs_namenode_port spark_version] | [kill rstudio_home container_id project_user_name]"
+    echo "usage: $0 [start rstudio_home hadoop_home project_user_name port secret_dir certs_dir
+    image_name logfile server_password hadoop_version hdfs_namenode_ip hdfs_namenode_port spark_version] | [kill rstudio_home container_id project_user_name]"
     echo ""
     exit 1
 }
 
-DOMAINS_DIR=/srv/hops/domains
-RSTUDIO_USER=yarnapp
-RSTUDIO_GROUP=hadoop
-HOPSWORKS_USER=glassfish
-VALID_IMAGE_NAME='^([a-z0-9]+(-[a-z0-9]+)*.)*[a-z0-9]+(:[0-9]*)?(/([a-zA-Z0-9-]*))?/([-:._a-zA-Z0-9]{0,62}[-:.a-zA-Z0-9]$)'
+
+DOMAINS_DIR=<%= node['glassfish']['domains_dir'] %>
+RSTUDIO_USER=<%= node['hops']['yarnapp']['user'] %>
+RSTUDIO_GROUP=<%= node['hops']['group'] %>
+HOPSWORKS_USER=<%= node['hopsworks']['user'] %>
+VALID_IMAGE_NAME='<%= node['conda']['docker']['image-validation-regex'] %>'
 
 if [ "$1" == "kill" ] ; then
+
     if [ $# -ne 4 ]; then
         help
     fi
@@ -137,7 +139,10 @@ elif [ "$1" == "generate_pems" ]; then
     echo $KEY | keytool -deststoretype PKCS12 -keystore $CERTS_DIR/${HADOOP_USERNAME}__tstore.p12 -list
     echo $KEY | openssl pkcs12 -nokeys -in $CERTS_DIR/${HADOOP_USERNAME}__tstore.p12 -out $CERTS_DIR/${HADOOP_USERNAME}_root_ca.pem
 
-    #3. verify that files have been generated
+    #3 extract private key from the keystore
+    echo $KEY | openssl pkcs12 -info -in $CERTS_DIR/${HADOOP_USERNAME}__keystore.p12 -nodes -nocerts > $CERTS_DIR/${HADOOP_USERNAME}_private_key.pem
+
+    #4. verify that files have been generated
     CERTIFICATES_BUNDLE=$CERTS_DIR/${HADOOP_USERNAME}_certificate_bundle.pem
     if [ ! -f ${CERTIFICATES_BUNDLE} ]; then
       echo "Failed to generate certificates bundle for project"
@@ -148,11 +153,71 @@ elif [ "$1" == "generate_pems" ]; then
       echo "Failed to generate root ca for project"
       exit 5
     fi
+    PRIVATE_KEY=$CERTS_DIR/${HADOOP_USERNAME}_private_key.pem
+    if [ ! -f ${PRIVATE_KEY} ]; then
+      echo "Failed to generate private key for project"
+      exit 6
+    fi
+
+    chmod 644 $ROOT_CA
+    chmod 644 $CERTIFICATES_BUNDLE
+    chmod 644 $PRIVATE_KEY
+
+    chown glassfish:glassfish $ROOT_CA
+    chown glassfish:glassfish $CERTIFICATES_BUNDLE
+    chown glassfish:glassfish $PRIVATE_KEY
 
     rm $CERTS_DIR/${HADOOP_USERNAME}__keystore.p12
     rm $CERTS_DIR/${HADOOP_USERNAME}__tstore.p12
+
+    #put root and intermidiate cas in one pem
+    #Define the string to split
+    CERT_BUNDLE_TEXT=$( cat $CERTIFICATES_BUNDLE )
+
+    #Define multi-character delimiter
+    DELIMETER="-----END CERTIFICATE-----"
+    #Concatenate the delimiter with the main string
+    STRDELIM=$CERT_BUNDLE_TEXT$DELIMETER
+
+    #Split the text based on the delimiter
+        #put root and intermidiate cas in one pem
+    #Define the string to split
+    CERT_BUNDLE_TEXT=$( cat $CERTIFICATES_BUNDLE)
+
+    #Define multi-character delimiter
+    DELIMETER="-----END CERTIFICATE-----"
+    #Concatenate the delimiter with the main string
+    STRDELIM=$CERT_BUNDLE_TEXT$DELIMETER
+
+    #Split the text based on the delimiter
+    STR_ARRAY=()
+    while [[ $STRDELIM ]]; do
+      STR_ARRAY+=( "${STRDELIM%%"$DELIMETER"*}" )
+      STRDELIM=${STRDELIM#*"$DELIMETER"}
+    done
+
+    INTERMEDIATE_CA=${STR_ARRAY[0]}
+
+    DELIMETER="-----BEGIN CERTIFICATE-----"
+
+    STRDELIM=$INTERMEDIATE_CA$DELIMETER
+    STR_ARRAY=()
+    while [[ $STRDELIM ]]; do
+      STR_ARRAY+=( "${STRDELIM%%"$DELIMETER"*}" )
+      STRDELIM=${STRDELIM#*"$DELIMETER"}
+    done
+
+    PROCESSED=${STR_ARRAY[1]}
+
+    cp $CERTS_DIR/${HADOOP_USERNAME}_root_ca.pem $CERTS_DIR/${HADOOP_USERNAME}_ca_bundle.pem
+
+    echo "-----BEGIN CERTIFICATE-----" >> $CERTS_DIR/${HADOOP_USERNAME}_ca_bundle.pem
+    echo  $PROCESSED | tr " " "\n" >> $CERTS_DIR/${HADOOP_USERNAME}_ca_bundle.pem
+    echo "-----END CERTIFICATE-----" >> $CERTS_DIR/${HADOOP_USERNAME}_ca_bundle.pem
+
+    chmod 644 $CERTS_DIR/${HADOOP_USERNAME}_ca_bundle.pem
+    chown glassfish:glassfish $CERTS_DIR/${HADOOP_USERNAME}_ca_bundle.pem
+
 else
   help
 fi
-
-
